# Generated by Django 3.1.2 on 2020-12-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogsearchkeywordmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('total_count', models.IntegerField(default=0)),
            ],
        ),
    ]
