# Generated by Django 3.1.2 on 2020-12-08 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201208_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcommentmodel',
            name='blog_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogmodel'),
        ),
    ]
