# Generated by Django 3.1.2 on 2020-11-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofilemodel',
            name='phone_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
