# Generated by Django 3.1.2 on 2020-11-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_companyprofilemodel_phone_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofilemodel',
            old_name='phone_num',
            new_name='phone',
        ),
    ]
