# Generated by Django 3.1.2 on 2020-11-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_preferredjobmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofilemodel',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
