# Generated by Django 3.1.2 on 2020-11-28 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_employeesearchkeywordmodel_jobsearchkeywordmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesearchkeywordmodel',
            name='searched_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobsearchkeywordmodel',
            name='searched_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
