# Generated by Django 3.1.2 on 2020-11-29 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201128_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantprofilemodel',
            old_name='upload',
            new_name='resume',
        ),
    ]
