# Generated by Django 3.1.2 on 2020-12-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201129_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofilemodel',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='applicantprofilemodel',
            name='totalRating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='applicantprofilemodel',
            name='totalRatingCount',
            field=models.IntegerField(default=0),
        ),
    ]
