# Generated by Django 3.1.2 on 2020-12-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201202_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofilemodel',
            name='avg_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofilemodel',
            name='totalRating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
