# Generated by Django 3.1.2 on 2020-12-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201202_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofilemodel',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='applicantprofilemodel',
            name='totalRating',
        ),
        migrations.RemoveField(
            model_name='applicantprofilemodel',
            name='totalRatingCount',
        ),
    ]
