# Generated by Django 3.1.2 on 2020-12-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20201204_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofilemodel',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
