# Generated by Django 3.1.2 on 2020-12-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20201224_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperiencemodel',
            name='company',
            field=models.CharField(default='nazia', max_length=255),
        ),
    ]
