# Generated by Django 3.1.2 on 2020-12-22 14:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_appliedjobmodel_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
