# Generated by Django 3.1.2 on 2020-12-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20201222_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='experience',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
