# Generated by Django 3.1.2 on 2020-12-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20201222_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
