# Generated by Django 3.1.2 on 2020-12-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20201222_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobmodel',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
