# Generated by Django 3.1.2 on 2020-12-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_appliedjobmodel_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobmodel',
            name='percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
