# Generated by Django 3.1.2 on 2020-12-22 20:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20201223_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilledJobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
