# Generated by Django 3.1.2 on 2020-12-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20201223_0348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilledJobModel',
        ),
    ]
