# Generated by Django 3.1.2 on 2020-12-23 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_auto_20201223_0842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilledJobModel',
        ),
    ]
