# Generated by Django 3.1.2 on 2020-12-23 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_filledjobmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilledJobModel',
        ),
    ]
