# Generated by Django 3.1.2 on 2020-12-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_filledjobmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filledjobmodel',
            name='company',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
