# Generated by Django 3.1.2 on 2020-12-23 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_auto_20201223_0907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilledJobModel',
        ),
    ]
