# Generated by Django 3.1.2 on 2020-12-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_delete_filledjobmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilledJobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=1000, null=True)),
                ('job', models.CharField(blank=True, max_length=1000, null=True)),
                ('feedback', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
