# Generated by Django 3.1.2 on 2020-12-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='course_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
